language: dart
dart:
  - stable
  - beta
  - dev
sudo: required
addons:
  chrome: stable

before_install:
- nvm install node
- node --version

script:
  - cd repo_support
  - dart pub get
  - dart run tool/travis.dart

# Only building master means that we don't run two builds for each pull request.
# branches:
#  only:
#    - master
#    - dart2

cache:
  directories:
    - $HOME/.pub-cache