name: tekartik_js_utils_repo
description: js_utils repo (tools)
version: 0.2.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.9.0 <3.0.0'

dev_dependencies:
  test: ">=1.2.0"
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.9.3+2'
  dev_test: any
  process_run:
  pedantic:

