name: tekartik_js_utils_interop
description: Javascript (js/wasm) utilities
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.9.3+2'

dev_dependencies:
  lints: ">=5.0.0"
  test: '>=1.24.0'
