name: repo_support
description: Repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ">=5.0.0"
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'

dependency_overrides:
  # Temp
  # tekartik_app_node_build:
  #  path: ../../app_node_utils.dart/app_build

