name: tekartik_js_utils
version: 0.2.0-nullsafety.0
description: Javascript utils

homepage: https://github.com/tekartik/js_utils.dart
publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  synchronized: '>=2.0.0'
  js: '>=0.6.2'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.9.3+2'
  stack_trace: '>=1.10.0'
dev_dependencies:
  process_run: '>=0.10.0+1'
  dev_test: '>=0.15.0'
  test: '>=1.16.3'
  build_runner: '>=1.11.1'
  build_test: '>=1.3.6'
  build_web_compilers: '>=2.12.0'
dependency_overrides:
#  build_node_compilers: '>=0.0.0'