name: tekartik_js_utils
version: 0.3.0
description: Javascript utils

homepage: https://github.com/tekartik/js_utils.dart
publish_to: none
environment:
  sdk: ^3.6.0
dependencies:
  synchronized: '>=2.0.0'
  js: '>=0.6.2'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.9.3+2'
  stack_trace: '>=1.10.0'
dev_dependencies:
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.0+2"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: '>=1.3.6'
  build_web_compilers: ">=4.0.11"
dependency_overrides:
#  build_node_compilers: '>=0.0.0'

